In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("02) IMDB Dataset.csv")

In [3]:
df.shape

(50000, 2)

In [4]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(418)

In [7]:
df.drop_duplicates(inplace = True)

In [8]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [9]:
df.shape

(49582, 2)

## Pre-Processing

### i) Converting to lowercase

In [10]:
df["review"] = df["review"].str.lower()

In [11]:
df["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

### ii) Removing URLs

In [12]:
import re

In [13]:
def remove_urls(text):
    text = re.sub(r"http\S+", "", text)
    return text

df["review"] = df["review"].apply(remove_urls)

### iii) Removing punctuations

In [14]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [15]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

### iv) Removing HTML

In [16]:
def remove_html(text):
    text = re.sub(r"<.*?>", "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [17]:
df["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production br br the filmin...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

### v) Removing Stopwords

In [18]:
import nltk

In [19]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\naiks\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\naiks\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\naiks\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [21]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")
    return text

In [22]:
df["review"] = df["review"].apply(remove_stopwords)

In [23]:
df["review"]

0        e    revewers  nted   wtchg  1 oz epode ll  ho...
1         wderful ltle producti br br  filming techniqu...
2         thought ths   wderful wy  spend tme   o hot s...
3        bsclly res  fmly   lttle boy jke thks res  zom...
4        petter mtte love   time  mey   vully stunng fi...
                               ...
49995     thought ths move dd   rght good job t wsnt s ...
49996    bd plot bd dlogue bd ctng dotc drectng  nnoyng...
49997       ctholc tught n prochl elentry schools  nuns...
49998    im gog    dgree   previous comnt  side  mlt   ...
49999     one expects  str trek moves   hgh rt   fns  e...
Name: review, Length: 49582, dtype: object

### vi) Stemming

In [24]:
from nltk.stem import PorterStemmer

In [25]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

In [26]:
df["review"] = df["review"].apply(stemming)

In [27]:
df["review"]

0        e revew nted wtchg 1 oz epod ll hook y rght ex...
1        wder ltle producti br br film techniqu unssum ...
2        thought th wder wy spend tme o hot summer week...
3        bsclli re fmli lttle boy jke thk re zomb close...
4        petter mtte love time mey vulli stunng film wt...
                               ...
49995    thought th move dd rght good job t wsnt s cret...
49996    bd plot bd dlogu bd ctng dotc drectng nnoyng p...
49997    ctholc tught n prochl elentri school nun tught...
49998    im gog dgree previou comnt side mlt e secd rte...
49999    one expect str trek move hgh rt fn expect move...
Name: review, Length: 49582, dtype: object

### vii) Encoding

In [28]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

y = df["sentiment"]

In [29]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### viii) Vectorization

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features = 5000)

x = tf.fit_transform(df["review"])

In [31]:
x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>

In [32]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2868)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3002)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4369)	0.041994187696759305
  (0, 4171)	0.17799685402440263
  (0, 3693)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3805)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4497)	0.07614066339174266
  (0, 3857)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4494)	0.09410069396961679
  (49581, 434)	0.11251655954741112
  (49581, 4277)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 555)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4347)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3647)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 527)	0.1247934452922504
  (49581, 2621)	0.17341357547872566
  (49581, 4458)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4033)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2695)	0.1740080872946952
  (49581, 439)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

## Dataset and DataLoaders

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [35]:
x_train.shape

(39665, 5000)

In [36]:
x_test.shape

(9917, 5000)

In [39]:
import torch
from torch.utils.data import TensorDataset, DataLoader

ModuleNotFoundError: No module named 'torch'

In [ ]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [ ]:
train_set = TensorDataset(
    torch.from_numpy(x_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(x_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [ ]:
train_loader = DataLoader(train_set, shuffle = True, batch_size = 64)
test_loader = DataLoader(test_set, shuffle = True, batch_size = 64)

## Building the RNN

In [ ]:
import torch.nn as nn
import torch.optim as optimizer

In [ ]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size = 128, num_layers = 1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first = True)

        # Fully Connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)
        out, _ = self.rnn(x, h0)
        out = self.fc(out[:, -1, :])
        
        return out

## Model

In [ ]:
input_size = x_train.shape[1]

model = RNN(input_size)

critetion = nn.BCELoss()

optimizer = optimizer.Adam(model.parameters())

## Training the RNN

In [ ]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for xb, yb in train_loader:
        optimizer.zero_grad

        xb = xb.unsqueeze(1)
        outputs = model(xb)

        outputs = torch.sigmoid(outputs.squeeze())

        loss = critetion(outputs, yb)

        loss.backward()

        optimizer.step()
        print(f"{epoch + 1}/{epochs} and loss = {loss.item()}")

1/10 and loss = 0.6863899230957031
1/10 and loss = 0.6868563890457153
1/10 and loss = 0.6734388470649719
1/10 and loss = 0.6924207210540771
1/10 and loss = 0.691792905330658
1/10 and loss = 0.7127077579498291
1/10 and loss = 0.6774889230728149
1/10 and loss = 0.6982181668281555
1/10 and loss = 0.6995368003845215
1/10 and loss = 0.7083249092102051
1/10 and loss = 0.6904383301734924
1/10 and loss = 0.6989181637763977
1/10 and loss = 0.6736702919006348
1/10 and loss = 0.6941774487495422
1/10 and loss = 0.662729024887085
1/10 and loss = 0.6776604652404785
1/10 and loss = 0.672730565071106
1/10 and loss = 0.6734280586242676
1/10 and loss = 0.6676016449928284
1/10 and loss = 0.6683514714241028
1/10 and loss = 0.6473056674003601
1/10 and loss = 0.6677361726760864
1/10 and loss = 0.6798094511032104
1/10 and loss = 0.6572743654251099
1/10 and loss = 0.6279686093330383
1/10 and loss = 0.6430493593215942
1/10 and loss = 0.6546506285667419
1/10 and loss = 0.6376782059669495
1/10 and loss = 0.6386877298355103
1/10 and loss = 0.6679462790489197
1/10 and loss = 0.6053401231765747
1/10 and loss = 0.6469223499298096
1/10 and loss = 0.6328366994857788
1/10 and loss = 0.63311368227005
1/10 and loss = 0.6780995726585388
1/10 and loss = 0.630565881729126
1/10 and loss = 0.6435034275054932
1/10 and loss = 0.5934014916419983
1/10 and loss = 0.6953970193862915
1/10 and loss = 0.6700270175933838
1/10 and loss = 0.6308947205543518
1/10 and loss = 0.6365686655044556
1/10 and loss = 0.5818585753440857
1/10 and loss = 0.5876731276512146
1/10 and loss = 0.5863100290298462
1/10 and loss = 0.5428085327148438
1/10 and loss = 0.5627278089523315
1/10 and loss = 0.551284909248352
1/10 and loss = 0.5699183344841003
1/10 and loss = 0.5272085070610046
1/10 and loss = 0.5552687644958496
1/10 and loss = 0.5938657522201538
1/10 and loss = 0.5513160228729248
1/10 and loss = 0.49419698119163513
1/10 and loss = 0.5107887983322144
1/10 and loss = 0.518494725227356
1/10 and loss = 0.49855124950408936
1/10 and loss = 0.4876156747341156
1/10 and loss = 0.5452606081962585
1/10 and loss = 0.5428367853164673
1/10 and loss = 0.5486891865730286
1/10 and loss = 0.525016188621521
1/10 and loss = 0.6340979337692261
1/10 and loss = 0.6011406183242798
1/10 and loss = 0.5108560919761658
1/10 and loss = 0.43661025166511536
1/10 and loss = 0.5537617802619934
1/10 and loss = 0.6014866232872009
1/10 and loss = 0.5683853626251221
1/10 and loss = 0.6574028134346008
1/10 and loss = 0.60577392578125
1/10 and loss = 0.49108558893203735
1/10 and loss = 0.5700731873512268
1/10 and loss = 0.6764726638793945
1/10 and loss = 0.6195849776268005
1/10 and loss = 0.43239399790763855
1/10 and loss = 0.4263516962528229
1/10 and loss = 0.6508176922798157
1/10 and loss = 0.556586742401123
1/10 and loss = 0.5899132490158081
1/10 and loss = 0.48545026779174805
1/10 and loss = 0.6564453840255737
1/10 and loss = 0.4789431691169739
1/10 and loss = 0.5253402590751648
1/10 and loss = 0.43563002347946167
1/10 and loss = 0.4341283440589905
1/10 and loss = 0.4035240411758423
1/10 and loss = 0.34323054552078247
1/10 and loss = 0.5072078704833984
1/10 and loss = 0.408827543258667
1/10 and loss = 0.30357626080513
1/10 and loss = 0.44779446721076965
1/10 and loss = 0.4738488495349884
1/10 and loss = 0.5840939283370972
1/10 and loss = 0.6518694758415222
1/10 and loss = 0.5547102689743042
1/10 and loss = 0.3855740427970886
1/10 and loss = 0.7176956534385681
1/10 and loss = 0.8134649991989136
1/10 and loss = 0.6022984981536865
1/10 and loss = 0.4989497661590576
1/10 and loss = 0.5149151086807251
1/10 and loss = 0.6289438009262085
1/10 and loss = 0.7044059038162231
1/10 and loss = 0.6967464685440063
1/10 and loss = 0.7304184436798096
1/10 and loss = 0.8518207669258118
1/10 and loss = 0.9259240627288818
1/10 and loss = 1.1010148525238037
1/10 and loss = 1.2829828262329102
1/10 and loss = 0.8677077293395996
1/10 and loss = 1.3526471853256226
1/10 and loss = 1.027937412261963
1/10 and loss = 0.8128157258033752
1/10 and loss = 0.9128192663192749
1/10 and loss = 0.7773888111114502
1/10 and loss = 0.6739794611930847
1/10 and loss = 0.6607394814491272
1/10 and loss = 0.8570285439491272
1/10 and loss = 0.6235303282737732
1/10 and loss = 0.6012072563171387
1/10 and loss = 0.5985739231109619
1/10 and loss = 0.6439005136489868
1/10 and loss = 0.4341147840023041
1/10 and loss = 0.4495719075202942
1/10 and loss = 0.451987087726593
1/10 and loss = 0.41918519139289856
1/10 and loss = 0.4108662009239197
1/10 and loss = 0.6214598417282104
1/10 and loss = 0.5114380121231079
1/10 and loss = 0.3686425983905792
1/10 and loss = 0.34555280208587646
1/10 and loss = 0.26985931396484375
1/10 and loss = 0.41062283515930176
1/10 and loss = 0.44462916254997253
1/10 and loss = 0.4289186894893646
1/10 and loss = 0.5688134431838989
1/10 and loss = 0.4999021291732788
1/10 and loss = 0.46790653467178345
1/10 and loss = 0.5631662011146545
1/10 and loss = 0.7388144135475159
1/10 and loss = 0.8397303819656372
1/10 and loss = 0.8542496562004089
1/10 and loss = 0.6252537369728088
1/10 and loss = 0.5025908946990967
1/10 and loss = 0.709201455116272
1/10 and loss = 1.1030508279800415
1/10 and loss = 1.016756296157837
1/10 and loss = 0.7152220010757446
1/10 and loss = 0.8773496747016907
1/10 and loss = 0.9733622670173645
1/10 and loss = 1.2536351680755615
1/10 and loss = 1.067786455154419
1/10 and loss = 0.9569845795631409
1/10 and loss = 1.0402295589447021
1/10 and loss = 1.2223860025405884
1/10 and loss = 1.3519080877304077
1/10 and loss = 1.2485425472259521
1/10 and loss = 0.9526780843734741
1/10 and loss = 0.8397210836410522
1/10 and loss = 0.7976916432380676
1/10 and loss = 1.2303898334503174
1/10 and loss = 1.0669684410095215
1/10 and loss = 0.9831421375274658
1/10 and loss = 0.9583754539489746
1/10 and loss = 0.6715258359909058
1/10 and loss = 0.6725668907165527
1/10 and loss = 0.9237244725227356
1/10 and loss = 0.7426930665969849
1/10 and loss = 0.7366400957107544
1/10 and loss = 0.7364957332611084
1/10 and loss = 0.7023884654045105
1/10 and loss = 0.7276011109352112
1/10 and loss = 0.5928202271461487
1/10 and loss = 0.5899161100387573
1/10 and loss = 0.5818918943405151
1/10 and loss = 0.6593549251556396
1/10 and loss = 0.609515368938446
1/10 and loss = 0.6720659732818604
1/10 and loss = 0.6026172637939453
1/10 and loss = 0.607686460018158
1/10 and loss = 0.6034007668495178
1/10 and loss = 0.5961999297142029
1/10 and loss = 0.6156205534934998
1/10 and loss = 0.6213241219520569
1/10 and loss = 0.6472282409667969
1/10 and loss = 0.7029280066490173
1/10 and loss = 0.7216273546218872
1/10 and loss = 0.7454217672348022
1/10 and loss = 0.822757363319397
1/10 and loss = 0.7784057259559631
1/10 and loss = 0.8310624957084656
1/10 and loss = 0.9607592225074768
1/10 and loss = 0.9049056768417358
1/10 and loss = 1.0327786207199097
1/10 and loss = 1.0035821199417114
1/10 and loss = 1.296958565711975
1/10 and loss = 1.3112332820892334
1/10 and loss = 1.3713868856430054
1/10 and loss = 1.2652322053909302
1/10 and loss = 1.4916143417358398
1/10 and loss = 1.4039770364761353
1/10 and loss = 1.4251182079315186
1/10 and loss = 1.1226599216461182
1/10 and loss = 1.126973271369934
1/10 and loss = 1.5757675170898438
1/10 and loss = 1.5288193225860596
1/10 and loss = 1.6128575801849365
1/10 and loss = 1.2985706329345703
1/10 and loss = 1.336878776550293
1/10 and loss = 1.3664836883544922
1/10 and loss = 1.7025625705718994
1/10 and loss = 1.1387028694152832
1/10 and loss = 1.3329434394836426
1/10 and loss = 1.1723464727401733
1/10 and loss = 1.3740878105163574
1/10 and loss = 1.2061048746109009
1/10 and loss = 1.4452362060546875
1/10 and loss = 1.0187197923660278
1/10 and loss = 1.2783355712890625
1/10 and loss = 1.1441943645477295
1/10 and loss = 0.8931457996368408
1/10 and loss = 0.9785585999488831
1/10 and loss = 0.9006528854370117
1/10 and loss = 1.015516996383667
1/10 and loss = 0.8966092467308044
1/10 and loss = 0.8448095321655273
1/10 and loss = 0.8558723330497742
1/10 and loss = 0.7125818729400635
1/10 and loss = 0.6831247210502625
1/10 and loss = 0.7343447208404541
1/10 and loss = 0.6844733953475952
1/10 and loss = 0.5378393530845642
1/10 and loss = 0.6247879862785339
1/10 and loss = 0.5051048994064331
1/10 and loss = 0.4503619074821472
1/10 and loss = 0.45483264327049255
1/10 and loss = 0.4237003028392792
1/10 and loss = 0.48317471146583557
1/10 and loss = 0.44140416383743286
1/10 and loss = 0.4906938076019287
1/10 and loss = 0.4690883457660675
1/10 and loss = 0.3947065770626068
1/10 and loss = 0.4124056100845337
1/10 and loss = 0.39977753162384033
1/10 and loss = 0.39782965183258057
1/10 and loss = 0.402317613363266
1/10 and loss = 0.3486611843109131
1/10 and loss = 0.30718129873275757
1/10 and loss = 0.5280368328094482
1/10 and loss = 0.383620023727417
1/10 and loss = 0.42994797229766846
1/10 and loss = 0.4372938275337219
1/10 and loss = 0.48779213428497314
1/10 and loss = 0.45320677757263184
1/10 and loss = 0.3263436257839203
1/10 and loss = 0.288779616355896
1/10 and loss = 0.4116875231266022
1/10 and loss = 0.43936336040496826
1/10 and loss = 0.4780837893486023
1/10 and loss = 0.587434709072113
1/10 and loss = 0.28561222553253174
1/10 and loss = 0.36882901191711426
1/10 and loss = 0.4996856153011322
1/10 and loss = 0.37145403027534485
1/10 and loss = 0.4731086790561676
1/10 and loss = 0.3451159596443176
1/10 and loss = 0.8198597431182861
1/10 and loss = 0.6132932901382446
1/10 and loss = 0.7491260170936584
1/10 and loss = 0.33281564712524414
1/10 and loss = 0.43905386328697205
1/10 and loss = 0.24049034714698792
1/10 and loss = 0.5937849879264832
1/10 and loss = 0.5476071238517761
1/10 and loss = 0.29973119497299194
1/10 and loss = 0.4372272491455078
1/10 and loss = 0.4633082449436188
1/10 and loss = 0.37331101298332214
1/10 and loss = 0.31326770782470703
1/10 and loss = 0.41335824131965637
1/10 and loss = 0.5605098605155945
1/10 and loss = 0.2506543695926666
1/10 and loss = 0.2731325626373291
1/10 and loss = 0.6459237933158875
1/10 and loss = 0.4203806519508362
1/10 and loss = 0.33969202637672424
1/10 and loss = 0.6321017742156982
1/10 and loss = 0.484907329082489
1/10 and loss = 0.3339874744415283
1/10 and loss = 0.35810232162475586
1/10 and loss = 0.3425307869911194
1/10 and loss = 0.4352037310600281
1/10 and loss = 0.640772819519043
1/10 and loss = 0.4768853187561035
1/10 and loss = 0.30581703782081604
1/10 and loss = 0.33183643221855164
1/10 and loss = 0.6326872706413269
1/10 and loss = 0.533801257610321
1/10 and loss = 0.42082253098487854
1/10 and loss = 0.4834808111190796
1/10 and loss = 0.31643104553222656
1/10 and loss = 0.8097710609436035
1/10 and loss = 0.502472996711731
1/10 and loss = 0.5587924122810364
1/10 and loss = 0.7445997595787048
1/10 and loss = 0.5534259080886841
1/10 and loss = 0.7219889163970947
1/10 and loss = 0.6626215577125549
1/10 and loss = 0.833060085773468
1/10 and loss = 0.7791746854782104
1/10 and loss = 0.618057131767273
1/10 and loss = 0.681443452835083
1/10 and loss = 0.6349003314971924
1/10 and loss = 1.259148120880127
1/10 and loss = 0.7973060607910156
1/10 and loss = 0.9142924547195435
1/10 and loss = 0.9971185922622681
1/10 and loss = 1.0423942804336548
1/10 and loss = 0.5176195502281189
1/10 and loss = 0.7603482007980347
1/10 and loss = 0.6968511939048767
1/10 and loss = 0.6141583323478699
1/10 and loss = 0.4781515896320343
1/10 and loss = 0.9011871218681335
1/10 and loss = 1.1438796520233154
1/10 and loss = 0.9688426852226257
1/10 and loss = 0.5066903233528137
1/10 and loss = 0.939538836479187
1/10 and loss = 0.7332072854042053
1/10 and loss = 0.5545142292976379
1/10 and loss = 0.8261573314666748
1/10 and loss = 1.122153878211975
1/10 and loss = 0.8545774221420288
1/10 and loss = 1.103688359260559
1/10 and loss = 1.1799970865249634
1/10 and loss = 0.6783298254013062
1/10 and loss = 0.6219426989555359
1/10 and loss = 1.116448163986206
1/10 and loss = 0.5938149690628052
1/10 and loss = 0.5075269341468811
1/10 and loss = 0.8550306558609009
1/10 and loss = 0.5897871255874634
1/10 and loss = 0.7316489219665527
1/10 and loss = 1.2094229459762573
1/10 and loss = 1.2804912328720093
1/10 and loss = 0.6620936989784241
1/10 and loss = 0.920153021812439
1/10 and loss = 0.3609582185745239
1/10 and loss = 0.43562835454940796
1/10 and loss = 0.9811331033706665
1/10 and loss = 0.8060237169265747
1/10 and loss = 0.44557857513427734
1/10 and loss = 0.5271716117858887
1/10 and loss = 0.6088114380836487
1/10 and loss = 0.970008373260498
1/10 and loss = 0.6971869468688965
1/10 and loss = 0.45610809326171875
1/10 and loss = 0.7934814095497131
1/10 and loss = 0.9772883653640747
1/10 and loss = 0.8473212718963623
1/10 and loss = 0.9238952994346619
1/10 and loss = 0.3321520686149597
1/10 and loss = 0.5949770212173462
1/10 and loss = 0.3283575177192688
1/10 and loss = 0.996117115020752
1/10 and loss = 0.8804916143417358
1/10 and loss = 0.6795455813407898
1/10 and loss = 1.3032772541046143
1/10 and loss = 0.5556561350822449
1/10 and loss = 0.2509525716304779
1/10 and loss = 1.0861735343933105
1/10 and loss = 0.5509111881256104
1/10 and loss = 0.6684450507164001
1/10 and loss = 1.1872363090515137
1/10 and loss = 1.429226040840149
1/10 and loss = 0.7475488781929016
1/10 and loss = 0.7061492204666138
1/10 and loss = 0.7406277656555176
1/10 and loss = 1.6484543085098267
1/10 and loss = 1.114517092704773
1/10 and loss = 1.0578023195266724
1/10 and loss = 1.4743459224700928
1/10 and loss = 0.7501009106636047
1/10 and loss = 3.5767996311187744
1/10 and loss = 1.323464035987854
1/10 and loss = 2.9207077026367188
1/10 and loss = 1.6122239828109741
1/10 and loss = 0.6918085813522339
1/10 and loss = 1.0437153577804565
1/10 and loss = 1.0870847702026367
1/10 and loss = 2.8724024295806885
1/10 and loss = 4.593035697937012
1/10 and loss = 0.80084627866745
1/10 and loss = 0.7485994696617126
1/10 and loss = 1.3122732639312744
1/10 and loss = 1.1097773313522339
1/10 and loss = 1.8584944009780884
1/10 and loss = 1.0300025939941406
1/10 and loss = 2.406630754470825
1/10 and loss = 1.0253880023956299
1/10 and loss = 0.7989025115966797
1/10 and loss = 1.8603379726409912
1/10 and loss = 1.160085678100586
1/10 and loss = 1.024399995803833
1/10 and loss = 6.325883865356445
1/10 and loss = 2.708012580871582
1/10 and loss = 2.9634807109832764
1/10 and loss = 0.6529762148857117
1/10 and loss = 1.235213041305542
1/10 and loss = 0.8743423819541931
1/10 and loss = 0.48210129141807556
1/10 and loss = 1.4450657367706299
1/10 and loss = 1.0827802419662476
1/10 and loss = 1.1466073989868164
1/10 and loss = 0.9955496191978455
1/10 and loss = 0.975899338722229
1/10 and loss = 0.6675029993057251
1/10 and loss = 0.8606453537940979
1/10 and loss = 0.7516671419143677
1/10 and loss = 0.7639315724372864
1/10 and loss = 0.7128885388374329
1/10 and loss = 1.0031522512435913
1/10 and loss = 0.5386860370635986
1/10 and loss = 0.5396565794944763
1/10 and loss = 0.7760530710220337
1/10 and loss = 1.032331109046936
1/10 and loss = 0.4023701548576355
1/10 and loss = 0.972183346748352
1/10 and loss = 3.8613815307617188
1/10 and loss = 0.762087345123291
1/10 and loss = 1.0664496421813965
1/10 and loss = 2.619459867477417
1/10 and loss = 0.7383041381835938
1/10 and loss = 0.5537769794464111
1/10 and loss = 1.0001035928726196
1/10 and loss = 1.4634233713150024
1/10 and loss = 0.9947729110717773
1/10 and loss = 1.1874643564224243
1/10 and loss = 0.9091400504112244
1/10 and loss = 1.2467825412750244
1/10 and loss = 0.713482141494751
1/10 and loss = 1.354312777519226
1/10 and loss = 0.6479405164718628
1/10 and loss = 0.7821587920188904
1/10 and loss = 1.6977003812789917
1/10 and loss = 0.40000519156455994
1/10 and loss = 1.0575737953186035
1/10 and loss = 1.0001040697097778
1/10 and loss = 1.5865319967269897
1/10 and loss = 1.457953929901123
1/10 and loss = 1.792281150817871
1/10 and loss = 1.0385769605636597
1/10 and loss = 1.0055668354034424
1/10 and loss = 1.6598165035247803
1/10 and loss = 1.8301681280136108
1/10 and loss = 1.6528350114822388
1/10 and loss = 1.4915533065795898
1/10 and loss = 1.880969762802124
1/10 and loss = 0.7415224313735962
1/10 and loss = 2.0664772987365723
1/10 and loss = 1.9154605865478516
1/10 and loss = 2.126662015914917
1/10 and loss = 1.1050095558166504
1/10 and loss = 1.3625291585922241
1/10 and loss = 1.7417467832565308
1/10 and loss = 1.8837392330169678
1/10 and loss = 1.2761183977127075
1/10 and loss = 0.813491940498352
1/10 and loss = 1.8625999689102173
1/10 and loss = 1.8357090950012207
1/10 and loss = 1.394830346107483
1/10 and loss = 1.7805054187774658
1/10 and loss = 1.7196663618087769
1/10 and loss = 1.2751953601837158
1/10 and loss = 1.2669568061828613
1/10 and loss = 1.2898401021957397
1/10 and loss = 1.7010388374328613
1/10 and loss = 1.0842641592025757
1/10 and loss = 0.9946892261505127
1/10 and loss = 1.4915066957473755
1/10 and loss = 1.4531311988830566
1/10 and loss = 1.1081165075302124
1/10 and loss = 1.131484031677246
1/10 and loss = 0.8335538506507874
1/10 and loss = 1.3806960582733154
1/10 and loss = 1.4842841625213623
1/10 and loss = 0.9822297096252441
1/10 and loss = 0.5948853492736816
1/10 and loss = 0.6174403429031372
1/10 and loss = 0.6537468433380127
1/10 and loss = 1.1116942167282104
1/10 and loss = 0.5665106773376465
1/10 and loss = 0.7031115889549255
1/10 and loss = 0.6632158756256104
1/10 and loss = 0.6756709218025208
1/10 and loss = 0.7243975400924683
1/10 and loss = 0.8416224718093872
1/10 and loss = 0.8519323468208313
1/10 and loss = 0.3870309293270111
1/10 and loss = 0.9153717756271362
1/10 and loss = 0.5866841077804565
1/10 and loss = 0.5061428546905518
1/10 and loss = 0.6786174178123474
1/10 and loss = 0.39350301027297974
1/10 and loss = 0.6389510035514832
1/10 and loss = 0.7667729258537292
1/10 and loss = 0.7269957661628723
1/10 and loss = 0.459564208984375
1/10 and loss = 0.7427526116371155
1/10 and loss = 0.8153631687164307
1/10 and loss = 1.2995163202285767
1/10 and loss = 0.9847796559333801
1/10 and loss = 0.5828053951263428
1/10 and loss = 1.1463912725448608
1/10 and loss = 0.993417501449585
1/10 and loss = 1.2804151773452759
1/10 and loss = 0.8809232711791992
1/10 and loss = 0.837216854095459
1/10 and loss = 1.3072718381881714
1/10 and loss = 1.331496238708496
1/10 and loss = 1.7272379398345947
1/10 and loss = 1.592145562171936
1/10 and loss = 1.392828106880188
1/10 and loss = 3.8284194469451904
1/10 and loss = 1.5767062902450562
1/10 and loss = 1.9704563617706299
1/10 and loss = 2.164396286010742
1/10 and loss = 1.8409433364868164
1/10 and loss = 1.8061774969100952
1/10 and loss = 2.415512800216675
1/10 and loss = 2.1451292037963867
1/10 and loss = 2.011744260787964
1/10 and loss = 3.2127082347869873
1/10 and loss = 3.152761936187744
1/10 and loss = 2.522291898727417
1/10 and loss = 3.2371745109558105
1/10 and loss = 2.493529796600342
1/10 and loss = 2.269320249557495
1/10 and loss = 1.9847768545150757
1/10 and loss = 1.9202392101287842
1/10 and loss = 2.2692065238952637
1/10 and loss = 3.2172274589538574
1/10 and loss = 2.0210695266723633
1/10 and loss = 2.9739327430725098
1/10 and loss = 2.273224353790283
1/10 and loss = 1.286778211593628
1/10 and loss = 2.4522202014923096
1/10 and loss = 1.8840092420578003
1/10 and loss = 1.594276785850525
1/10 and loss = 3.0810229778289795
1/10 and loss = 2.5969574451446533
1/10 and loss = 1.6332236528396606
1/10 and loss = 1.925047755241394
1/10 and loss = 1.348743200302124
1/10 and loss = 1.2239845991134644
1/10 and loss = 3.228081226348877
1/10 and loss = 1.8709261417388916
1/10 and loss = 1.9988754987716675
1/10 and loss = 1.7919020652770996
1/10 and loss = 1.8147424459457397
1/10 and loss = 1.6358941793441772
1/10 and loss = 1.8899872303009033
1/10 and loss = 1.7277940511703491
1/10 and loss = 1.2386797666549683
1/10 and loss = 1.2595545053482056
1/10 and loss = 1.6253536939620972
1/10 and loss = 1.1420800685882568
1/10 and loss = 0.8211383819580078
1/10 and loss = 1.4831565618515015
1/10 and loss = 0.7645621299743652
1/10 and loss = 0.6665173768997192

## Evaluation

In [ ]:
model.eval()

with torch.no_grad():
    correct_vals = 0
    total_vals = 0

    for xb, yb in test_loader:
        xb = xb.unsqueeze(1)
        outputs = model(xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        total_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {(correct_vals / total_vals)*100}")

accuracy = 81.86951699102552